/**
 * Artifact generators derived from the contract: `.env.example`, TypeScript
 * declarations, and Markdown documentation. None of these ever emit a secret
 * value — `.env.example` leaves secret values blank by design.
 */

import type { Contract, VariableDef, VariableType } from '../types.js';

/** Maps a contract type to a TypeScript type expression. */
function tsType(def: VariableDef): string {
  switch (def.type) {
    case 'integer':
    case 'number':
    case 'port':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enum':
      return def.values && def.values.length ? def.values.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    case 'list':
      return 'string[]';
    case 'json':
      return 'unknown';
    default:
      return 'string';
  }
}

/** A short, human label for a type (used in comments/docs). */
function typeLabel(type: VariableType): string {
  return type;
}

/** Generates `.env.example` text from the contract. */
export function generateExample(contract: Contract): string {
  const lines: string[] = [
    '# Generated by envcanary — do not edit by hand.',
    '# Run `envcanary generate example` to refresh.',
    '',
  ];

  for (const [name, def] of Object.entries(contract.variables)) {
    if (def.description) lines.push(`# ${def.description}`);
    const meta: string[] = [typeLabel(def.type)];
    if (def.requiredIn?.length) meta.push(`required in: ${def.requiredIn.join(', ')}`);
    if (def.secret) meta.push('secret');
    if (def.owner) meta.push(`owner: ${def.owner}`);
    lines.push(`# (${meta.join(' · ')})`);

    // Secrets are never written with a value; non-secrets may show a default.
    const value = def.secret ? '' : def.default !== undefined ? String(def.default) : '';
    lines.push(`${name}=${value}`);
    lines.push('');
  }

  return lines.join('\n');
}

/** Generates a `.d.ts` describing the validated environment shape. */
export function generateTypes(contract: Contract): string {
  const lines: string[] = [
    '// Generated by envcanary — do not edit by hand.',
    '// Run `envcanary generate types` to refresh.',
    '',
    'export interface Env {',
  ];
  for (const [name, def] of Object.entries(contract.variables)) {
    if (def.description) lines.push(`  /** ${def.description} */`);
    const optional = def.requiredIn && def.requiredIn.length > 0 ? '' : '?';
    lines.push(`  ${name}${optional}: ${tsType(def)};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** Generates a Markdown reference table from the contract. */
export function generateDocs(contract: Contract): string {
  const lines: string[] = [
    '# Environment Configuration',
    '',
    `Contract version: ${contract.contractVersion}`,
    '',
    `Environments: ${contract.environments.join(', ')}`,
    '',
    '| Variable | Type | Required in | Secret | Exposure | Owner | Description |',
    '|---|---|---|---|---|---|---|',
  ];
  for (const [name, def] of Object.entries(contract.variables)) {
    lines.push(
      `| \`${name}\` | ${def.type} | ${def.requiredIn?.join(', ') ?? '—'} | ${def.secret ? 'yes' : 'no'} | ${def.exposure ?? '—'} | ${def.owner ?? '—'} | ${def.description ?? ''} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
